[CmdletBinding()]
param(
    [switch]$Check
)

$ErrorActionPreference = 'Stop'

$governanceRoot = Split-Path -Parent $PSScriptRoot
$workspaceRoot = Split-Path -Parent $governanceRoot
$profilePath = Join-Path $governanceRoot 'build\graphical-profile\profile.json'
$profileDocument = Get-Content -Raw -Path $profilePath | ConvertFrom-Json

function New-GeneratedSource {
    param(
        [Parameter(Mandatory)]
        [string]$Namespace
    )

    $lines = [System.Collections.Generic.List[string]]::new()
    [void]$lines.Add('// <auto-generated />')
    [void]$lines.Add('// Generated by novolis-governance/scripts/Export-GraphicalProfile.ps1.')
    [void]$lines.Add('#nullable enable')
    [void]$lines.Add('#pragma warning disable CS1591')
    [void]$lines.Add('')
    [void]$lines.Add("namespace $Namespace;")
    [void]$lines.Add('')
    [void]$lines.Add('/// <summary>Generated values from the governance graphical profile bundle.</summary>')
    [void]$lines.Add('public static class GraphicalProfileColors')
    [void]$lines.Add('{')

    foreach ($property in $profileDocument.roles.psobject.Properties) {
        $name = $property.Name
        $pascal = $name.Substring(0, 1).ToUpperInvariant() + $name.Substring(1)
        $dark = $property.Value.dark
        $light = $property.Value.light
        [void]$lines.Add("    public const string ${pascal}Dark = `"$dark`";")
        [void]$lines.Add("    public const string ${pascal}Light = `"$light`";")
    }

    [void]$lines.Add('')
    foreach ($property in $profileDocument.typography.psobject.Properties) {
        $name = $property.Name
        $pascal = $name.Substring(0, 1).ToUpperInvariant() + $name.Substring(1)
        $value = $property.Value
        if ($value -is [string]) {
            [void]$lines.Add("    public const string $pascal = `"$value`";")
        } else {
            [void]$lines.Add("    public const double $pascal = $value;")
        }
    }

    [void]$lines.Add('')
    foreach ($property in $profileDocument.geometry.psobject.Properties) {
        $name = $property.Name
        $pascal = $name.Substring(0, 1).ToUpperInvariant() + $name.Substring(1)
        $value = $property.Value
        [void]$lines.Add("    public const double $pascal = $value;")
    }

    [void]$lines.Add('}')
    [void]$lines.Add('')
    return ($lines -join [Environment]::NewLine)
}

$targets = @(
    @{
        Path = Join-Path $workspaceRoot 'novolis-avalonia\src\Novolis.Avalonia.GraphicalProfile\Generated\GraphicalProfileColors.g.cs'
        Namespace = 'Novolis.Avalonia.GraphicalProfile'
    },
    @{
        Path = Join-Path $workspaceRoot 'novolis-maui\src\Novolis.Maui.GraphicalProfile\Generated\GraphicalProfileColors.g.cs'
        Namespace = 'Novolis.Maui.GraphicalProfile'
    }
)

function ConvertTo-NormalizedText {
    param([string]$Text)
    return ($Text -replace "`r`n", "`n").TrimEnd()
}

$failed = $false
foreach ($target in $targets) {
    $content = New-GeneratedSource -Namespace $target.Namespace
    if ($Check) {
        if (-not (Test-Path $target.Path) -or
            (ConvertTo-NormalizedText (Get-Content -Raw -Path $target.Path)) -ne (ConvertTo-NormalizedText $content)) {
            Write-Error "Generated graphical profile is stale: $($target.Path)"
            $failed = $true
        }
        continue
    }

    $directory = Split-Path -Parent $target.Path
    New-Item -ItemType Directory -Path $directory -Force | Out-Null
    [System.IO.File]::WriteAllText(
        $target.Path,
        $content,
        [System.Text.UTF8Encoding]::new($false))
    Write-Host "Generated $($target.Path)"
}

if ($failed) {
    exit 1
}
