// Export graphical profile JSON to Avalonia/MAUI C# constants and site CSS.
//
//   dotnet run --file d:\novolis\novolis-governance\scripts\Export-GraphicalProfile.cs
//   dotnet run --file d:\novolis\novolis-governance\scripts\Export-GraphicalProfile.cs -- --check

#:property TargetFramework=net10.0
#:property PublishAot=false
#:property PackAsTool=false
#:property ImplicitUsings=enable
#:property Nullable=enable
#:property ManagePackageVersionsCentrally=false

using System.Globalization;
using System.Runtime.CompilerServices;
using System.Text;
using System.Text.Json;
using System.Text.RegularExpressions;

var check = args.Any(a => string.Equals(a, "--check", StringComparison.OrdinalIgnoreCase)
    || string.Equals(a, "-Check", StringComparison.OrdinalIgnoreCase)
    || string.Equals(a, "-check", StringComparison.OrdinalIgnoreCase));

var scripts = Path.GetDirectoryName(GetScriptPath())!;
var governanceRoot = Directory.GetParent(scripts)!.FullName;
var workspaceRoot = Directory.GetParent(governanceRoot)!.FullName;
var profilePath = Path.Combine(governanceRoot, "build", "graphical-profile", "profile.json");
using var profileStream = File.OpenRead(profilePath);
var profile = JsonDocument.Parse(profileStream).RootElement;

var targets = new (string Path, string Kind, string? Namespace)[]
{
    (Path.Combine(workspaceRoot, "novolis-avalonia", "src", "Novolis.Avalonia.GraphicalProfile", "Generated", "GraphicalProfileColors.g.cs"), "csharp", "Novolis.Avalonia.GraphicalProfile"),
    (Path.Combine(workspaceRoot, "novolis-maui", "src", "Novolis.Maui.GraphicalProfile", "Generated", "GraphicalProfileColors.g.cs"), "csharp", "Novolis.Maui.GraphicalProfile"),
    (Path.Combine(workspaceRoot, ".github", "site", "assets", "profile.css"), "css", null),
    (Path.Combine(workspaceRoot, "novolis-blazor", "src", "Novolis.Blazor.GraphicalProfile", "wwwroot", "css", "graphical-profile.css"), "css", null),
};

var failed = false;
foreach (var target in targets)
{
    var content = target.Kind == "css"
        ? NewGeneratedCss(profile)
        : NewGeneratedSource(profile, target.Namespace!);

    if (check)
    {
        if (!File.Exists(target.Path) || Normalize(File.ReadAllText(target.Path)) != Normalize(content))
        {
            Console.Error.WriteLine($"Generated graphical profile is stale: {target.Path}");
            failed = true;
        }

        continue;
    }

    Directory.CreateDirectory(Path.GetDirectoryName(target.Path)!);
    File.WriteAllText(target.Path, content, new UTF8Encoding(encoderShouldEmitUTF8Identifier: false));
    Console.WriteLine($"Generated {target.Path}");
}

return failed ? 1 : 0;

static string NewGeneratedSource(JsonElement profile, string ns)
{
    var lines = new List<string>
    {
        "// <auto-generated />",
        "// Generated by novolis-governance/scripts/Export-GraphicalProfile.ps1.",
        "#nullable enable",
        "#pragma warning disable CS1591",
        "",
        $"namespace {ns};",
        "",
        "/// <summary>Generated values from the governance graphical profile bundle.</summary>",
        "public static class GraphicalProfileColors",
        "{",
    };

    foreach (var property in profile.GetProperty("roles").EnumerateObject())
    {
        var pascal = ToPascal(property.Name);
        lines.Add($"    public const string {pascal}Dark = \"{property.Value.GetProperty("dark").GetString()}\";");
        lines.Add($"    public const string {pascal}Light = \"{property.Value.GetProperty("light").GetString()}\";");
    }

    lines.Add("");
    foreach (var property in profile.GetProperty("typography").EnumerateObject())
    {
        var pascal = ToPascal(property.Name);
        if (property.Value.ValueKind == JsonValueKind.String)
            lines.Add($"    public const string {pascal} = \"{property.Value.GetString()}\";");
        else
            lines.Add($"    public const double {pascal} = {FormatNumber(property.Value)};");
    }

    lines.Add("");
    foreach (var property in profile.GetProperty("geometry").EnumerateObject())
    {
        var pascal = ToPascal(property.Name);
        lines.Add($"    public const double {pascal} = {FormatNumber(property.Value)};");
    }

    lines.Add("}");
    lines.Add("");
    return string.Join(Environment.NewLine, lines);
}

static string NewGeneratedCss(JsonElement profile)
{
    var lines = new List<string>
    {
        "/* <auto-generated />",
        "   Generated by novolis-governance/scripts/Export-GraphicalProfile.ps1.",
        "   Do not hand-edit. */",
        "",
        ":root {",
        "  color-scheme: dark;",
    };

    foreach (var property in profile.GetProperty("roles").EnumerateObject())
        lines.Add($"  --ngp-{ToKebab(property.Name)}: {property.Value.GetProperty("dark").GetString()};");

    foreach (var property in profile.GetProperty("typography").EnumerateObject())
    {
        var token = property.Name switch
        {
            "fontFamily" => "--ngp-font",
            "monoFontFamily" => "--ngp-font-mono",
            _ => "--ngp-" + ToKebab(property.Name),
        };
        if (property.Value.ValueKind == JsonValueKind.String)
            lines.Add($"  {token}: {property.Value.GetString()};");
        else
            lines.Add($"  {token}: {FormatNumber(property.Value)}px;");
    }

    foreach (var property in profile.GetProperty("geometry").EnumerateObject())
        lines.Add($"  --ngp-{ToKebab(property.Name)}: {FormatNumber(property.Value)}px;");

    lines.Add("}");
    lines.Add("");
    lines.Add("@media (prefers-color-scheme: light) {");
    lines.Add("  :root {");
    lines.Add("    color-scheme: light;");
    foreach (var property in profile.GetProperty("roles").EnumerateObject())
        lines.Add($"    --ngp-{ToKebab(property.Name)}: {property.Value.GetProperty("light").GetString()};");
    lines.Add("  }");
    lines.Add("}");
    lines.Add("");
    return string.Join(Environment.NewLine, lines);
}

static string ToPascal(string name) =>
    string.IsNullOrEmpty(name) ? name : char.ToUpperInvariant(name[0]) + name[1..];

static string ToKebab(string name) =>
    Regex.Replace(name, "([a-z0-9])([A-Z])", "$1-$2").ToLowerInvariant();

static string FormatNumber(JsonElement value) =>
    value.ValueKind == JsonValueKind.Number
        ? value.GetRawText()
        : Convert.ToString(value.GetDouble(), CultureInfo.InvariantCulture) ?? "0";

static string Normalize(string text) => text.Replace("\r\n", "\n").TrimEnd();

static string GetScriptPath([CallerFilePath] string path = "") => path;
